name: Python release

on:
  push:
    tags:
      - v*

env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_DIST }}

permissions: {}

jobs:
  python_release:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - name: Set up Python
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools wheel
    - run: python setup.py sdist bdist_wheel

    - run: |
        pip install twine
    - name: Upload to PyPi
      run: |
          twine upload dist/* -u __token__ -p "$PYPI_TOKEN"
